#!/usr/bin/perl

# Usage
#
# chmod-644-755 <path> <file-umask> <directory-umask>
# 
# For example:
# chmod-644-755 public_html/ 640 700
#
# The defaults are:
#            path : ./
#      file-umask : 644 
# directory-umask : 755

use Getopt::Long;

# Options
my $fmask = 644;
my $dmask = 755;
my $result = GetOptions ( "f=i" => \$fmask,
                          "d=i" => \$dmask  );
# Path
my $path = $ARGV[0] || "./";

print "$fmask\n$dmask\n$path\n";

# (The extra backslash is to escape the backslash in perl so that it appears in the bash call)
system ("find $path -type f -exec chmod $fmask '{}' \\;");
system ("find $path -type d -exec chmod $dmask '{}' \\;");



#sub main {
#  my ($path, $fmask, $dmask) = @_;
#  $path    ||= '.';
#  $fmask ||= "644";
#  $dmask ||= "755";
#
#  # (The extra backslash is to escape the backslash in perl so that it appears in the bash call)
#  system ("find $path -type f -exec chmod $fmask '{}' \\;");
#  system ("find $path -type d -exec chmod $dmask '{}' \\;");
#}
#
#main (@ARGV);
